name: toxicity-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - imbalanced-learn
  - rdkit
  - xgboost
  - lightgbm
  - pytorch
  - shap
  - lime
  - pip
  - pip:
      - streamlit
